-- Decompiled using luadec 2.1 r80 from http://code.google.com/p/luadec
-- Command line: C:\TrSSO\WorkFold\COMP\RAW\2.76\script\map\npclist.lua 
local _t = require("i18n").context("map")
NpcList = {}
local MAP_NPCMARK_ALL = 1
local MAP_NPCMARK_NORMAL_TASK = 2
local MAP_NPCMARK_IMPORT_TASK = 3
local MAP_NPCMARK_TELEPORT = 4
local MAP_NPCMARK_IMPORT_PLACE = 5
local MAP_NPCMARK_FUNCTION = 6
local MAP_NPCMARK_MASTER = 7
NpcList[100] = {instance = 1, 
list = {
{id = 341, name = _t("Test1"), category = MAP_NPCMARK_ALL}, 
{id = 341, name = _t("Test2"), category = MAP_NPCMARK_NORMAL_TASK}, 
{id = 341, name = _t("Test3"), category = MAP_NPCMARK_IMPORT_TASK}}, 
[0] = {
{id = 341, name = _t("Test4"), category = MAP_NPCMARK_FUNCTION}, 
{id = 341, name = _t("Test5"), category = MAP_NPCMARK_MASTER}, 
{id = 341, name = _t("Test6"), category = MAP_NPCMARK_TELEPORT}}}
NpcList[1] = {instance = 1, 
list = {
{id = 11564, name = _t("Warehouse"), category = MAP_NPCMARK_FUNCTION}, 
{id = 11568, name = _t("Mailbox"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20814, name = _t("Potion Seller"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20815, name = _t("Merchant"), category = MAP_NPCMARK_FUNCTION}, 
{id = 11320, name = _t("Blacksmith"), category = MAP_NPCMARK_FUNCTION}, 
{id = 15808, name = _t("Teleport"), category = MAP_NPCMARK_TELEPORT}, 
{id = 13903, name = _t("City"), category = MAP_NPCMARK_FUNCTION}}}
NpcList[2] = {instance = 2, 
list = {
{id = 11569, name = _t("Mailbox"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20816, name = _t("Warehouse"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20817, name = _t("Potion Seller"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20818, name = _t("Merchant"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20819, name = _t("Blacksmith"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20812, name = _t("Enhancer"), category = MAP_NPCMARK_FUNCTION}, 
{id = 15593, name = _t("Teleport"), category = MAP_NPCMARK_TELEPORT}, 
{id = 20820, name = _t("City"), category = MAP_NPCMARK_TELEPORT}}}
NpcList[3] = {instance = 3, 
list = {
{id = 11567, name = _t("Warehouse"), category = MAP_NPCMARK_FUNCTION}, 
{id = 11571, name = _t("Mailbox"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20823, name = _t("Potion Seller"), category = MAP_NPCMARK_FUNCTION}, 
{id = 11323, name = _t("Blacksmith"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20824, name = _t("Merchant"), category = MAP_NPCMARK_FUNCTION}, 
{id = 15594, name = _t("Teleport"), category = MAP_NPCMARK_TELEPORT}, 
{id = 20825, name = _t("City"), category = MAP_NPCMARK_FUNCTION}, 
{id = 11578, name = _t("Enhancer"), category = MAP_NPCMARK_FUNCTION}}, 
[401] = {
{id = 11581, name = _t("Artisan"), category = MAP_NPCMARK_FUNCTION}}}
NpcList[4] = {instance = 4, 
list = {
{id = 20826, name = _t("Warehouse"), category = MAP_NPCMARK_FUNCTION}, 
{id = 11570, name = _t("Mailbox"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20827, name = _t("Merchant"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20828, name = _t("Blacksmith"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20829, name = _t("Potion Seller"), category = MAP_NPCMARK_FUNCTION}, 
{id = 15595, name = _t("Teleport"), category = MAP_NPCMARK_TELEPORT}, 
{id = 20830, name = _t("City"), category = MAP_NPCMARK_FUNCTION}, 
{id = 11577, name = _t("Enhancer"), category = MAP_NPCMARK_FUNCTION}}, 
[301] = {
{id = 11580, name = _t("Artisan"), category = MAP_NPCMARK_FUNCTION}}, 
[307] = {
{id = 13599, name = _t("Artisan"), category = MAP_NPCMARK_FUNCTION}}}
NpcList[5] = {instance = 5, 
list = {
{id = 20242, name = _t("Mailbox"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20831, name = _t("Warehouse"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20832, name = _t("Merchant"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20833, name = _t("Blacksmith"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20834, name = _t("Potion Seller"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20642, name = _t("Teleport"), category = MAP_NPCMARK_TELEPORT}, 
{id = 20643, name = _t("City"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20243, name = _t("Enhancer"), category = MAP_NPCMARK_FUNCTION}}}
NpcList[6] = {instance = 6, 
list = {
{id = 20292, name = _t("Mailbox"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20641, name = _t("Warehouse"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20835, name = _t("Merchant"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20640, name = _t("Blacksmith"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20836, name = _t("Potion Seller"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20644, name = _t("Teleport"), category = MAP_NPCMARK_TELEPORT}, 
{id = 20645, name = _t("City"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20293, name = _t("Enhancer"), category = MAP_NPCMARK_FUNCTION}}}
NpcList[7] = {instance = 47, 
list = {
{id = 14918, name = _t("Fantasy Angel"), category = MAP_NPCMARK_FUNCTION}}}
NpcList[8] = {instance = 48, 
list = {
{id = 14919, name = _t("Fantasy Angel"), category = MAP_NPCMARK_FUNCTION}}}
NpcList[9] = {instance = 49, 
list = {
{id = 14920, name = _t("Fantasy Angel"), category = MAP_NPCMARK_FUNCTION}}}
NpcList[10] = {instance = 7, 
list = {
{id = 23680, name = _t("Teleport"), category = MAP_NPCMARK_TELEPORT}, 
{id = 23681, name = _t("City"), category = MAP_NPCMARK_FUNCTION}, 
{id = 23685, name = _t("Mailbox"), category = MAP_NPCMARK_FUNCTION}, 
{id = 23679, name = _t("Warehouse"), category = MAP_NPCMARK_FUNCTION}, 
{id = 23682, name = _t("Merchant"), category = MAP_NPCMARK_FUNCTION}, 
{id = 23686, name = _t("Blacksmith"), category = MAP_NPCMARK_FUNCTION}, 
{id = 23684, name = _t("Potion Seller"), category = MAP_NPCMARK_FUNCTION}, 
{id = 23689, name = _t("Enhancer"), category = MAP_NPCMARK_FUNCTION}}}
NpcList[11] = {instance = 8, 
list = {
{id = 25220, name = _t("Teleport"), category = MAP_NPCMARK_TELEPORT}, 
{id = 25221, name = _t("City"), category = MAP_NPCMARK_FUNCTION}, 
{id = 25224, name = _t("Mailbox"), category = MAP_NPCMARK_FUNCTION}, 
{id = 25219, name = _t("Warehouse"), category = MAP_NPCMARK_FUNCTION}, 
{id = 25222, name = _t("Merchant"), category = MAP_NPCMARK_FUNCTION}, 
{id = 25065, name = _t("Blacksmith"), category = MAP_NPCMARK_FUNCTION}, 
{id = 25223, name = _t("Potion Seller"), category = MAP_NPCMARK_FUNCTION}, 
{id = 25064, name = _t("Enhancer"), category = MAP_NPCMARK_FUNCTION}}}
NpcList[12] = {instance = 101, 
list = {
{id = 8519, name = _t("Base Architect"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8545, name = _t("Base Shop Manager"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8533, name = _t("Base Warehouse"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8554, name = _t("Base Training Ground"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8579, name = _t("Base Miracle"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8568, name = _t("Base Altar"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8563, name = _t("Base Workshop"), category = MAP_NPCMARK_FUNCTION}, 
{id = 17857, name = _t("Legion Practice"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20016, name = _t("Legion Card Exchange"), category = MAP_NPCMARK_FUNCTION}, 
{id = 13534, name = _t("Fortified"), category = MAP_NPCMARK_IMPORT_TASK}, 
{id = 20614, name = _t("Hermes"), category = MAP_NPCMARK_IMPORT_TASK}}}
NpcList[13] = {instance = 9, 
list = {
{id = 28351, name = _t("Teleport"), category = MAP_NPCMARK_TELEPORT}, 
{id = 28352, name = _t("City"), category = MAP_NPCMARK_FUNCTION}, 
{id = 28347, name = _t("Warehouse"), category = MAP_NPCMARK_FUNCTION}, 
{id = 28350, name = _t("Mailbox"), category = MAP_NPCMARK_FUNCTION}, 
{id = 28349, name = _t("Potion Seller"), category = MAP_NPCMARK_FUNCTION}, 
{id = 28348, name = _t("Merchant"), category = MAP_NPCMARK_FUNCTION}, 
{id = 28346, name = _t("Blacksmith"), category = MAP_NPCMARK_FUNCTION}, 
{id = 28341, name = _t("Enhancer"), category = MAP_NPCMARK_FUNCTION}}}
NpcList[14] = {instance = 10, 
list = {
{id = 28390, name = _t("Teleport"), category = MAP_NPCMARK_TELEPORT}, 
{id = 28391, name = _t("City"), category = MAP_NPCMARK_FUNCTION}, 
{id = 28380, name = _t("Mailbox"), category = MAP_NPCMARK_FUNCTION}, 
{id = 28416, name = _t("Warehouse"), category = MAP_NPCMARK_FUNCTION}, 
{id = 28392, name = _t("Merchant"), category = MAP_NPCMARK_FUNCTION}, 
{id = 28394, name = _t("Blacksmith"), category = MAP_NPCMARK_FUNCTION}, 
{id = 28393, name = _t("Potion Seller"), category = MAP_NPCMARK_FUNCTION}, 
{id = 28382, name = _t("Enhancer"), category = MAP_NPCMARK_FUNCTION}}}
NpcList[15] = {instance = 26, 
list = {
{id = 33773, name = _t("Main"), category = MAP_NPCMARK_TELEPORT}, 
{id = 33778, name = _t("SE ambassador"), category = MAP_NPCMARK_TELEPORT}, 
{id = 33779, name = _t("SW Herald"), category = MAP_NPCMARK_TELEPORT}, 
{id = 33780, name = _t("NE Messenger"), category = MAP_NPCMARK_TELEPORT}, 
{id = 33781, name = _t("NW Messenger"), category = MAP_NPCMARK_TELEPORT}}}
NpcList[16] = {instance = 27, 
list = {
{id = 33774, name = _t("Main"), category = MAP_NPCMARK_TELEPORT}, 
{id = 33782, name = _t("SE ambassador"), category = MAP_NPCMARK_TELEPORT}, 
{id = 33783, name = _t("SW Herald"), category = MAP_NPCMARK_TELEPORT}, 
{id = 33784, name = _t("NE Messenger"), category = MAP_NPCMARK_TELEPORT}, 
{id = 33785, name = _t("NW Messenger"), category = MAP_NPCMARK_TELEPORT}}}
NpcList[17] = {instance = 28, 
list = {
{id = 33775, name = _t("Main"), category = MAP_NPCMARK_TELEPORT}, 
{id = 33786, name = _t("SE ambassador"), category = MAP_NPCMARK_TELEPORT}, 
{id = 33787, name = _t("SW Herald"), category = MAP_NPCMARK_TELEPORT}, 
{id = 33788, name = _t("NE Messenger"), category = MAP_NPCMARK_TELEPORT}, 
{id = 33789, name = _t("NW Messenger"), category = MAP_NPCMARK_TELEPORT}}}
NpcList[18] = {instance = 29, 
list = {
{id = 33776, name = _t("Main"), category = MAP_NPCMARK_TELEPORT}, 
{id = 33790, name = _t("SE ambassador"), category = MAP_NPCMARK_TELEPORT}, 
{id = 33791, name = _t("SW Herald"), category = MAP_NPCMARK_TELEPORT}, 
{id = 33792, name = _t("NE Messenger"), category = MAP_NPCMARK_TELEPORT}, 
{id = 33793, name = _t("NW Messenger"), category = MAP_NPCMARK_TELEPORT}}}
NpcList[19] = {instance = 30, 
list = {
{id = 33777, name = _t("Main"), category = MAP_NPCMARK_TELEPORT}, 
{id = 33794, name = _t("SE ambassador"), category = MAP_NPCMARK_TELEPORT}, 
{id = 33795, name = _t("SW Herald"), category = MAP_NPCMARK_TELEPORT}, 
{id = 33796, name = _t("NE Messenger"), category = MAP_NPCMARK_TELEPORT}, 
{id = 33797, name = _t("NW Messenger"), category = MAP_NPCMARK_TELEPORT}}}
NpcList[20] = {instance = 31, 
list = {
{id = 34033, name = _t("Main"), category = MAP_NPCMARK_TELEPORT}, 
{id = 34034, name = _t("SE ambassador"), category = MAP_NPCMARK_TELEPORT}, 
{id = 34035, name = _t("SW Herald"), category = MAP_NPCMARK_TELEPORT}, 
{id = 34036, name = _t("NE Messenger"), category = MAP_NPCMARK_TELEPORT}, 
{id = 34037, name = _t("NW Messenger"), category = MAP_NPCMARK_TELEPORT}}}
NpcList[21] = {instance = 25, 
list = {
{id = 38000, name = _t("Aegean Bay"), category = MAP_NPCMARK_TELEPORT}, 
{id = 38001, name = _t("Cupid"), category = MAP_NPCMARK_FUNCTION}, 
{id = 38005, name = _t("Wedding preparation"), category = MAP_NPCMARK_FUNCTION}, 
{id = 38006, name = _t("Relatives and friends"), category = MAP_NPCMARK_FUNCTION}, 
{id = 38007, name = _t("Wedding Pastor"), category = MAP_NPCMARK_FUNCTION}}}
NpcList[22] = {instance = 11, 
list = {
{id = 41995, name = _t("Teleport"), category = MAP_NPCMARK_TELEPORT}, 
{id = 41996, name = _t("City"), category = MAP_NPCMARK_FUNCTION}, 
{id = 41998, name = _t("Supply"), category = MAP_NPCMARK_FUNCTION}}}
NpcList[23] = {instance = 18, 
list = {
{id = 200323, name = _t("Warehouse"), category = MAP_NPCMARK_FUNCTION}, 
{id = 200329, name = _t("Mailbox"), category = MAP_NPCMARK_FUNCTION}, 
{id = 200325, name = _t("Potion Seller"), category = MAP_NPCMARK_FUNCTION}, 
{id = 200324, name = _t("Merchant"), category = MAP_NPCMARK_FUNCTION}, 
{id = 200330, name = _t("Blacksmith"), category = MAP_NPCMARK_FUNCTION}, 
{id = 200296, name = _t("Teleport"), category = MAP_NPCMARK_TELEPORT}, 
{id = 200295, name = _t("City"), category = MAP_NPCMARK_FUNCTION}}}
NpcList[24] = {instance = 20, 
list = {
{id = 17286, name = _t("Merchant"), category = MAP_NPCMARK_FUNCTION}, 
{id = 11304, name = _t("Potion Seller"), category = MAP_NPCMARK_FUNCTION}, 
{id = 11577, name = _t("Enhancer"), category = MAP_NPCMARK_FUNCTION}, 
{id = 11322, name = _t("Blacksmith"), category = MAP_NPCMARK_FUNCTION}, 
{id = 11580, name = _t("Artisan"), category = MAP_NPCMARK_FUNCTION}, 
{id = 31619, name = _t("Permit Seller"), category = MAP_NPCMARK_FUNCTION}, 
{id = 11566, name = _t("Warehouse"), category = MAP_NPCMARK_FUNCTION}, 
{id = 11570, name = _t("Mailbox"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14630, name = _t("Quartermaster"), category = MAP_NPCMARK_FUNCTION}, 
{id = 13564, name = _t("Teleport"), category = MAP_NPCMARK_TELEPORT}, 
{id = 13585, name = _t("Back to the city"), category = MAP_NPCMARK_FUNCTION}, 
{id = 27365, name = _t("Therapist"), category = MAP_NPCMARK_FUNCTION}, 
{id = 17850, name = _t("Rune mosaic"), category = MAP_NPCMARK_FUNCTION}}, 
[2001] = {
{id = 17439, name = _t("[Merchant] Saint Clothing"), category = MAP_NPCMARK_FUNCTION}, 
{id = 34898, name = _t("[Merchant] Gold Messenger"), category = MAP_NPCMARK_FUNCTION}, 
{id = 39393, name = _t("[Merchant] Scales clothing"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14686, name = _t("[Merchant] Silver, gold guards"), category = MAP_NPCMARK_FUNCTION}, 
{id = 37275, name = _t("[Merchant] Constellation"), category = MAP_NPCMARK_FUNCTION}, 
{id = 29190, name = _t("[Merchant] Star soul"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20313, name = _t("[Merchant] Light of Hope"), category = MAP_NPCMARK_FUNCTION}, 
{id = 11575, name = _t("[Merchant] Auctioneer"), category = MAP_NPCMARK_FUNCTION}, 
{id = 33262, name = _t("[Merchant] Ribbons, belts"), category = MAP_NPCMARK_FUNCTION}, 
{id = 36329, name = _t("[Merchant] Artifact"), category = MAP_NPCMARK_FUNCTION}, 
{id = 43035, name = _t("[Merchant] Soul"), category = MAP_NPCMARK_FUNCTION}, 
{id = 18165, name = _t("[Merchant] Treasure"), category = MAP_NPCMARK_FUNCTION}, 
{id = 26471, name = _t("[Merchant] Title and Reputation"), category = MAP_NPCMARK_FUNCTION}, 
{id = 15578, name = _t("[Merchant] Oracle priest"), category = MAP_NPCMARK_FUNCTION}, 
{id = 31619, name = _t("[Merchant] Goddess of Mercy - Athenea"), category = MAP_NPCMARK_FUNCTION}, 
{id = 25893, name = _t("[Merchant] Heritage"), category = MAP_NPCMARK_FUNCTION}, 
{id = 17542, name = _t("[Merchant] Carpenter - Skills Learning"), category = MAP_NPCMARK_FUNCTION}, 
{id = 16359, name = _t("[Merchant] Rider"), category = MAP_NPCMARK_FUNCTION}, 
{id = 17341, name = _t("[Merchant] Pet"), category = MAP_NPCMARK_FUNCTION}, 
{id = 32331, name = _t("[Merchant] Treasure Hunt"), category = MAP_NPCMARK_FUNCTION}, 
{id = 29306, name = _t("[Merchant] Security card"), category = MAP_NPCMARK_FUNCTION}, 
{id = 22955, name = _t("[Info] Ruler"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14799, name = _t("[Info] Guild"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14799, name = _t("[Info] Guild Alliance"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14799, name = _t("[Info] Banner guard"), category = MAP_NPCMARK_FUNCTION}, 
{id = 51273, name = _t("[Info] Crusade！World BOSS"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20220, name = _t("[Info] Kill Evil"), category = MAP_NPCMARK_FUNCTION}, 
{id = 41938, name = _t("[Info] Gold powder exchange"), category = MAP_NPCMARK_FUNCTION}, 
{id = 30079, name = _t("[Info] Mopping"), category = MAP_NPCMARK_FUNCTION}, 
{id = 42851, name = _t("[Info] War God"), category = MAP_NPCMARK_FUNCTION}, 
{id = 30129, name = _t("[Core] Magic ring"), category = MAP_NPCMARK_FUNCTION}, 
{id = 41604, name = _t("[Core] Carnival"), category = MAP_NPCMARK_FUNCTION}, 
{id = 29138, name = _t("[Core] Welfare"), category = MAP_NPCMARK_FUNCTION}, 
{id = 35527, name = _t("[Core] Sanctuary Saints"), category = MAP_NPCMARK_FUNCTION}, 
{id = 32159, name = _t("[Core] Promotion - Fire"), category = MAP_NPCMARK_FUNCTION}, 
{id = 38489, name = _t("[Core] Event"), category = MAP_NPCMARK_FUNCTION}, 
{id = 18405, name = _t("[Tourney] Career change"), category = MAP_NPCMARK_FUNCTION}, 
{id = 16355, name = _t("[Tourney] Battlefield - Caitlinna"), category = MAP_NPCMARK_FUNCTION}, 
{id = 19317, name = _t("[Tourney] Battlefield rewards"), category = MAP_NPCMARK_FUNCTION}, 
{id = 34702, name = _t("[Tourney] Cloak Merchant"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14895, name = _t("[Tourney] Illusion"), category = MAP_NPCMARK_FUNCTION}, 
{id = 48412, name = _t("[Tourney] Galaxy Challenge - Cosmic Contest"), category = MAP_NPCMARK_FUNCTION}, 
{id = 42444, name = _t("[Tourney] Cross - Service competition"), category = MAP_NPCMARK_FUNCTION}, 
{id = 47528, name = _t("[Villa] Monthly Golden Week"), category = MAP_NPCMARK_FUNCTION}, 
{id = 30707, name = _t("[Villa] Holiday"), category = MAP_NPCMARK_FUNCTION}, 
{id = 29411, name = _t("[Villa] Goddess"), category = MAP_NPCMARK_FUNCTION}, 
{id = 50212, name = _t("[Villa] Anniversary Carnival"), category = MAP_NPCMARK_FUNCTION}, 
{id = 39769, name = _t("[Villa] Event"), category = MAP_NPCMARK_FUNCTION}, 
{id = 38428, name = _t("[Villa] Marriage - Divorce - Best friend"), category = MAP_NPCMARK_FUNCTION}, 
{id = 34575, name = _t("[Villa] Mentor"), category = MAP_NPCMARK_FUNCTION}}, 
[2002] = {
{id = 17439, name = _t("[Merchant] Bronze Crafter"), category = MAP_NPCMARK_FUNCTION}, 
{id = 17440, name = _t("[Merchant] White Silversmith"), category = MAP_NPCMARK_FUNCTION}, 
{id = 31003, name = _t("[Merchant] Dark crafter"), category = MAP_NPCMARK_FUNCTION}, 
{id = 28252, name = _t("[Merchant] Gold carpenter"), category = MAP_NPCMARK_FUNCTION}, 
{id = 34898, name = _t("[Merchant] Gold Messenger"), category = MAP_NPCMARK_FUNCTION}, 
{id = 39393, name = _t("[Merchant] Scale clothing"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14841, name = _t("[Merchant] Offerings clothing"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14686, name = _t("[Merchant] Silver guards"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14687, name = _t("[Merchant] Gold guards"), category = MAP_NPCMARK_FUNCTION}, 
{id = 37275, name = _t("[Merchant] Constellation"), category = MAP_NPCMARK_FUNCTION}, 
{id = 29190, name = _t("[Merchant] Star soul"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20313, name = _t("[Merchant] Light of Hope"), category = MAP_NPCMARK_FUNCTION}, 
{id = 11575, name = _t("[Merchant] Auctioneer"), category = MAP_NPCMARK_FUNCTION}, 
{id = 33262, name = _t("[Merchant] Ribbon"), category = MAP_NPCMARK_FUNCTION}, 
{id = 34694, name = _t("[Merchant] Belt"), category = MAP_NPCMARK_FUNCTION}, 
{id = 36329, name = _t("[Merchant] Artifact"), category = MAP_NPCMARK_FUNCTION}, 
{id = 43035, name = _t("[Merchant] Soul"), category = MAP_NPCMARK_FUNCTION}, 
{id = 18165, name = _t("[Merchant] Treasure"), category = MAP_NPCMARK_FUNCTION}, 
{id = 26471, name = _t("[Merchant] Title and Reputation"), category = MAP_NPCMARK_FUNCTION}, 
{id = 15578, name = _t("[Merchant] Oracle priest"), category = MAP_NPCMARK_FUNCTION}, 
{id = 31619, name = _t("[Merchant] Goddess of Mercy - Athenea"), category = MAP_NPCMARK_FUNCTION}, 
{id = 25893, name = _t("[Merchant] Heritage"), category = MAP_NPCMARK_FUNCTION}, 
{id = 16359, name = _t("[Merchant] Rider"), category = MAP_NPCMARK_FUNCTION}, 
{id = 17341, name = _t("[Merchant] Pet"), category = MAP_NPCMARK_FUNCTION}, 
{id = 32331, name = _t("[Merchant] Treasure Hunt"), category = MAP_NPCMARK_FUNCTION}, 
{id = 29306, name = _t("[Merchant] Security card"), category = MAP_NPCMARK_FUNCTION}, 
{id = 22955, name = _t("[Info] Ruler"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14799, name = _t("[Info] Guild"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14799, name = _t("[Info] Guild Alliance"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14799, name = _t("[Info] Banner guard"), category = MAP_NPCMARK_FUNCTION}, 
{id = 203238, name = _t("[Info] MAX! Unlimited Black Hole"), category = MAP_NPCMARK_FUNCTION}, 
{id = 13950, name = _t("[Info] Yihad Memories"), category = MAP_NPCMARK_FUNCTION}, 
{id = 13949, name = _t("[Info] Zodiac crisis - Sanctuary"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14420, name = _t("[Info] Atlantis - The Last Day of the Magic Star"), category = MAP_NPCMARK_FUNCTION}, 
{id = 50726, name = _t("[Info] Storm! Seal of the goddess"), category = MAP_NPCMARK_FUNCTION}, 
{id = 40463, name = _t("[Info] Resurrection! Myth battlefield "), category = MAP_NPCMARK_FUNCTION}, 
{id = 12839, name = _t("[Info] Gold trials - Counterattack - Lushan dream"), category = MAP_NPCMARK_FUNCTION}, 
{id = 211972, name = _t("[Info] Tried! Road of God"), category = MAP_NPCMARK_FUNCTION}, 
{id = 51273, name = _t("[Info] Crusade！World BOSS"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20220, name = _t("[Info] Kill Evil"), category = MAP_NPCMARK_FUNCTION}, 
{id = 41938, name = _t("[Info] Gold powder exchange"), category = MAP_NPCMARK_FUNCTION}, 
{id = 30079, name = _t("[Info] Mopping messengers"), category = MAP_NPCMARK_FUNCTION}, 
{id = 42851, name = _t("[Info] War God"), category = MAP_NPCMARK_FUNCTION}, 
{id = 9187, name = _t("[Info] Saint Goddess"), category = MAP_NPCMARK_FUNCTION}, 
{id = 201318, name = _t("[Info] Saint Seiya road"), category = MAP_NPCMARK_FUNCTION}, 
{id = 31592, name = _t("[Info] Sacred Commander"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8608, name = _t("[Core] Fate trials"), category = MAP_NPCMARK_FUNCTION}, 
{id = 30129, name = _t("[Core] Magic ring"), category = MAP_NPCMARK_FUNCTION}, 
{id = 41604, name = _t("[Core] Carnival"), category = MAP_NPCMARK_FUNCTION}, 
{id = 29138, name = _t("[Core] Welfare"), category = MAP_NPCMARK_FUNCTION}, 
{id = 35527, name = _t("[Core] Sanctuary Saints"), category = MAP_NPCMARK_FUNCTION}, 
{id = 32159, name = _t("[Core] Promotion - Fire"), category = MAP_NPCMARK_FUNCTION}, 
{id = 38489, name = _t("[Core] Event"), category = MAP_NPCMARK_FUNCTION}, 
{id = 18405, name = _t("[Tourney] Career change"), category = MAP_NPCMARK_FUNCTION}, 
{id = 16355, name = _t("[Tourney] Battlefield - Caitlinna"), category = MAP_NPCMARK_FUNCTION}, 
{id = 19317, name = _t("[Tourney] Battlefield rewards"), category = MAP_NPCMARK_FUNCTION}, 
{id = 34702, name = _t("[Tourney] Cloak Merchant"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14895, name = _t("[Tourney] Illusion"), category = MAP_NPCMARK_FUNCTION}, 
{id = 48412, name = _t("[Tourney] Galaxy Challenge - Cosmic Contest"), category = MAP_NPCMARK_FUNCTION}, 
{id = 42444, name = _t("[Tourney] Cross - Service competition"), category = MAP_NPCMARK_FUNCTION}, 
{id = 47528, name = _t("[Villa] Monthly Golden Week"), category = MAP_NPCMARK_FUNCTION}, 
{id = 30707, name = _t("[Villa] Holiday"), category = MAP_NPCMARK_FUNCTION}, 
{id = 29411, name = _t("[Villa] Goddess"), category = MAP_NPCMARK_FUNCTION}, 
{id = 50212, name = _t("[Villa] Anniversary Carnival"), category = MAP_NPCMARK_FUNCTION}, 
{id = 39769, name = _t("[Villa] Event"), category = MAP_NPCMARK_FUNCTION}, 
{id = 44451, name = _t("[Villa] Crisis! Saori Saints"), category = MAP_NPCMARK_FUNCTION}, 
{id = 44453, name = _t("[Villa] Critical! Goddess Saints"), category = MAP_NPCMARK_FUNCTION}, 
{id = 39671, name = _t("[Villa] Critical! Goddess of the mind"), category = MAP_NPCMARK_FUNCTION}, 
{id = 38428, name = _t("[Villa] Marriage - Divorce - Best friend"), category = MAP_NPCMARK_FUNCTION}, 
{id = 34575, name = _t("[Villa] Mentor"), category = MAP_NPCMARK_FUNCTION}}, 
[2003] = {
{id = 17439, name = _t("[Merchant] Bronze Crafter"), category = MAP_NPCMARK_FUNCTION}, 
{id = 17440, name = _t("[Merchant] White Silversmith"), category = MAP_NPCMARK_FUNCTION}, 
{id = 31003, name = _t("[Merchant] Dark crafter"), category = MAP_NPCMARK_FUNCTION}, 
{id = 28252, name = _t("[Merchant] Gold carpenter"), category = MAP_NPCMARK_FUNCTION}, 
{id = 34898, name = _t("[Merchant] Gold Messenger"), category = MAP_NPCMARK_FUNCTION}, 
{id = 39393, name = _t("[Merchant] Scale clothing"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14841, name = _t("[Merchant] Offerings clothing"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14686, name = _t("[Merchant] Silver guards"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14687, name = _t("[Merchant] Gold guards"), category = MAP_NPCMARK_FUNCTION}, 
{id = 37275, name = _t("[Merchant] Constellation"), category = MAP_NPCMARK_FUNCTION}, 
{id = 29190, name = _t("[Merchant] Star soul"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20313, name = _t("[Merchant] Light of Hope"), category = MAP_NPCMARK_FUNCTION}, 
{id = 11575, name = _t("[Merchant] Auctioneer"), category = MAP_NPCMARK_FUNCTION}, 
{id = 33262, name = _t("[Merchant] Ribbon"), category = MAP_NPCMARK_FUNCTION}, 
{id = 34694, name = _t("[Merchant] Belt"), category = MAP_NPCMARK_FUNCTION}, 
{id = 36329, name = _t("[Merchant] Artifact"), category = MAP_NPCMARK_FUNCTION}, 
{id = 43035, name = _t("[Merchant] Soul"), category = MAP_NPCMARK_FUNCTION}, 
{id = 18165, name = _t("[Merchant] Treasure"), category = MAP_NPCMARK_FUNCTION}, 
{id = 26471, name = _t("[Merchant] Title and Reputation"), category = MAP_NPCMARK_FUNCTION}, 
{id = 15578, name = _t("[Merchant] Oracle priest"), category = MAP_NPCMARK_FUNCTION}, 
{id = 31619, name = _t("[Merchant] Goddess of Mercy - Athenea"), category = MAP_NPCMARK_FUNCTION}, 
{id = 25893, name = _t("[Merchant] Heritage"), category = MAP_NPCMARK_FUNCTION}, 
{id = 16359, name = _t("[Merchant] Rider"), category = MAP_NPCMARK_FUNCTION}, 
{id = 17341, name = _t("[Merchant] Pet"), category = MAP_NPCMARK_FUNCTION}, 
{id = 32331, name = _t("[Merchant] Treasure Hunt"), category = MAP_NPCMARK_FUNCTION}, 
{id = 29306, name = _t("[Merchant] Security card"), category = MAP_NPCMARK_FUNCTION}, 
{id = 22955, name = _t("[Info] Ruler"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14799, name = _t("[Info] Guild"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14799, name = _t("[Info] Guild Alliance"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14799, name = _t("[Info] Banner guard"), category = MAP_NPCMARK_FUNCTION}, 
{id = 203238, name = _t("[Info] MAX! Unlimited Black Hole"), category = MAP_NPCMARK_FUNCTION}, 
{id = 13950, name = _t("[Info] Yihad Memories"), category = MAP_NPCMARK_FUNCTION}, 
{id = 13949, name = _t("[Info] Zodiac crisis - Sanctuary"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14420, name = _t("[Info] Atlantis - The Last Day of the Magic Star"), category = MAP_NPCMARK_FUNCTION}, 
{id = 50726, name = _t("[Info] Storm! Seal of the goddess"), category = MAP_NPCMARK_FUNCTION}, 
{id = 40463, name = _t("[Info] Resurrection! Myth battlefield "), category = MAP_NPCMARK_FUNCTION}, 
{id = 12839, name = _t("[Info] Gold trials - Counterattack - Lushan dream"), category = MAP_NPCMARK_FUNCTION}, 
{id = 211972, name = _t("[Info] Tried! Road of God"), category = MAP_NPCMARK_FUNCTION}, 
{id = 51273, name = _t("[Info] Crusade！World BOSS"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20220, name = _t("[Info] Kill Evil"), category = MAP_NPCMARK_FUNCTION}, 
{id = 41938, name = _t("[Info] Gold powder exchange"), category = MAP_NPCMARK_FUNCTION}, 
{id = 30079, name = _t("[Info] Mopping messengers"), category = MAP_NPCMARK_FUNCTION}, 
{id = 42851, name = _t("[Info] War God"), category = MAP_NPCMARK_FUNCTION}, 
{id = 9187, name = _t("[Info] Saint Goddess"), category = MAP_NPCMARK_FUNCTION}, 
{id = 201318, name = _t("[Info] Saint Seiya road"), category = MAP_NPCMARK_FUNCTION}, 
{id = 31592, name = _t("[Info] Sacred Commander"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8608, name = _t("[Core] Fate trials"), category = MAP_NPCMARK_FUNCTION}, 
{id = 30129, name = _t("[Core] Magic ring"), category = MAP_NPCMARK_FUNCTION}, 
{id = 41604, name = _t("[Core] Carnival"), category = MAP_NPCMARK_FUNCTION}, 
{id = 29138, name = _t("[Core] Welfare"), category = MAP_NPCMARK_FUNCTION}, 
{id = 35527, name = _t("[Core] Sanctuary Saints"), category = MAP_NPCMARK_FUNCTION}, 
{id = 32159, name = _t("[Core] Promotion - Fire"), category = MAP_NPCMARK_FUNCTION}, 
{id = 38489, name = _t("[Core] Event"), category = MAP_NPCMARK_FUNCTION}, 
{id = 18405, name = _t("[Tourney] Career change"), category = MAP_NPCMARK_FUNCTION}, 
{id = 16355, name = _t("[Tourney] Battlefield - Caitlinna"), category = MAP_NPCMARK_FUNCTION}, 
{id = 19317, name = _t("[Tourney] Battlefield rewards"), category = MAP_NPCMARK_FUNCTION}, 
{id = 34702, name = _t("[Tourney] Cloak Merchant"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14895, name = _t("[Tourney] Illusion"), category = MAP_NPCMARK_FUNCTION}, 
{id = 48412, name = _t("[Tourney] Galaxy Challenge - Cosmic Contest"), category = MAP_NPCMARK_FUNCTION}, 
{id = 42444, name = _t("[Tourney] Cross - Service competition"), category = MAP_NPCMARK_FUNCTION}, 
{id = 47528, name = _t("[Villa] Monthly Golden Week"), category = MAP_NPCMARK_FUNCTION}, 
{id = 30707, name = _t("[Villa] Holiday"), category = MAP_NPCMARK_FUNCTION}, 
{id = 29411, name = _t("[Villa] Goddess"), category = MAP_NPCMARK_FUNCTION}, 
{id = 50212, name = _t("[Villa] Anniversary Carnival"), category = MAP_NPCMARK_FUNCTION}, 
{id = 39769, name = _t("[Villa] Event"), category = MAP_NPCMARK_FUNCTION}, 
{id = 44451, name = _t("[Villa] Crisis! Saori Saints"), category = MAP_NPCMARK_FUNCTION}, 
{id = 44453, name = _t("[Villa] Critical! Goddess Saints"), category = MAP_NPCMARK_FUNCTION}, 
{id = 39671, name = _t("[Villa] Critical! Goddess of the mind"), category = MAP_NPCMARK_FUNCTION}, 
{id = 38428, name = _t("[Villa] Marriage - Divorce - Best friend"), category = MAP_NPCMARK_FUNCTION}, 
{id = 34575, name = _t("[Villa] Mentor"), category = MAP_NPCMARK_FUNCTION}}, 
[2004] = {
{id = 17439, name = _t("[Merchant] Bronze Crafter"), category = MAP_NPCMARK_FUNCTION}, 
{id = 17440, name = _t("[Merchant] White Silversmith"), category = MAP_NPCMARK_FUNCTION}, 
{id = 31003, name = _t("[Merchant] Dark crafter"), category = MAP_NPCMARK_FUNCTION}, 
{id = 28252, name = _t("[Merchant] Gold carpenter"), category = MAP_NPCMARK_FUNCTION}, 
{id = 34898, name = _t("[Merchant] Gold Messenger"), category = MAP_NPCMARK_FUNCTION}, 
{id = 39393, name = _t("[Merchant] Scale clothing"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14841, name = _t("[Merchant] Offerings clothing"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14686, name = _t("[Merchant] Silver guards"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14687, name = _t("[Merchant] Gold guards"), category = MAP_NPCMARK_FUNCTION}, 
{id = 37275, name = _t("[Merchant] Constellation"), category = MAP_NPCMARK_FUNCTION}, 
{id = 29190, name = _t("[Merchant] Star soul"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20313, name = _t("[Merchant] Light of Hope"), category = MAP_NPCMARK_FUNCTION}, 
{id = 11575, name = _t("[Merchant] Auctioneer"), category = MAP_NPCMARK_FUNCTION}, 
{id = 33262, name = _t("[Merchant] Ribbon"), category = MAP_NPCMARK_FUNCTION}, 
{id = 34694, name = _t("[Merchant] Belt"), category = MAP_NPCMARK_FUNCTION}, 
{id = 36329, name = _t("[Merchant] Artifact"), category = MAP_NPCMARK_FUNCTION}, 
{id = 43035, name = _t("[Merchant] Soul"), category = MAP_NPCMARK_FUNCTION}, 
{id = 18165, name = _t("[Merchant] Treasure"), category = MAP_NPCMARK_FUNCTION}, 
{id = 26471, name = _t("[Merchant] Title and Reputation"), category = MAP_NPCMARK_FUNCTION}, 
{id = 15578, name = _t("[Merchant] Oracle priest"), category = MAP_NPCMARK_FUNCTION}, 
{id = 31619, name = _t("[Merchant] Goddess of Mercy - Athenea"), category = MAP_NPCMARK_FUNCTION}, 
{id = 25893, name = _t("[Merchant] Heritage"), category = MAP_NPCMARK_FUNCTION}, 
{id = 16359, name = _t("[Merchant] Rider"), category = MAP_NPCMARK_FUNCTION}, 
{id = 17341, name = _t("[Merchant] Pet"), category = MAP_NPCMARK_FUNCTION}, 
{id = 32331, name = _t("[Merchant] Treasure Hunt"), category = MAP_NPCMARK_FUNCTION}, 
{id = 29306, name = _t("[Merchant] Security card"), category = MAP_NPCMARK_FUNCTION}, 
{id = 22955, name = _t("[Info] Ruler"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14799, name = _t("[Info] Guild"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14799, name = _t("[Info] Guild Alliance"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14799, name = _t("[Info] Banner guard"), category = MAP_NPCMARK_FUNCTION}, 
{id = 203238, name = _t("[Info] MAX! Unlimited Black Hole"), category = MAP_NPCMARK_FUNCTION}, 
{id = 13950, name = _t("[Info] Yihad Memories"), category = MAP_NPCMARK_FUNCTION}, 
{id = 13949, name = _t("[Info] Zodiac crisis - Sanctuary"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14420, name = _t("[Info] Atlantis - The Last Day of the Magic Star"), category = MAP_NPCMARK_FUNCTION}, 
{id = 50726, name = _t("[Info] Storm! Seal of the goddess"), category = MAP_NPCMARK_FUNCTION}, 
{id = 40463, name = _t("[Info] Resurrection! Myth battlefield "), category = MAP_NPCMARK_FUNCTION}, 
{id = 12839, name = _t("[Info] Gold trials - Counterattack - Lushan dream"), category = MAP_NPCMARK_FUNCTION}, 
{id = 211972, name = _t("[Info] Tried! Road of God"), category = MAP_NPCMARK_FUNCTION}, 
{id = 51273, name = _t("[Info] Crusade！World BOSS"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20220, name = _t("[Info] Kill Evil"), category = MAP_NPCMARK_FUNCTION}, 
{id = 41938, name = _t("[Info] Gold powder exchange"), category = MAP_NPCMARK_FUNCTION}, 
{id = 30079, name = _t("[Info] Mopping messengers"), category = MAP_NPCMARK_FUNCTION}, 
{id = 42851, name = _t("[Info] War God"), category = MAP_NPCMARK_FUNCTION}, 
{id = 9187, name = _t("[Info] Saint Goddess"), category = MAP_NPCMARK_FUNCTION}, 
{id = 201318, name = _t("[Info] Saint Seiya road"), category = MAP_NPCMARK_FUNCTION}, 
{id = 31592, name = _t("[Info] Sacred Commander"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8608, name = _t("[Core] Fate trials"), category = MAP_NPCMARK_FUNCTION}, 
{id = 30129, name = _t("[Core] Magic ring"), category = MAP_NPCMARK_FUNCTION}, 
{id = 41604, name = _t("[Core] Carnival"), category = MAP_NPCMARK_FUNCTION}, 
{id = 29138, name = _t("[Core] Welfare"), category = MAP_NPCMARK_FUNCTION}, 
{id = 35527, name = _t("[Core] Sanctuary Saints"), category = MAP_NPCMARK_FUNCTION}, 
{id = 32159, name = _t("[Core] Promotion - Fire"), category = MAP_NPCMARK_FUNCTION}, 
{id = 38489, name = _t("[Core] Event"), category = MAP_NPCMARK_FUNCTION}, 
{id = 18405, name = _t("[Tourney] Career change"), category = MAP_NPCMARK_FUNCTION}, 
{id = 16355, name = _t("[Tourney] Battlefield - Caitlinna"), category = MAP_NPCMARK_FUNCTION}, 
{id = 19317, name = _t("[Tourney] Battlefield rewards"), category = MAP_NPCMARK_FUNCTION}, 
{id = 34702, name = _t("[Tourney] Cloak Merchant"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14895, name = _t("[Tourney] Illusion"), category = MAP_NPCMARK_FUNCTION}, 
{id = 48412, name = _t("[Tourney] Galaxy Challenge - Cosmic Contest"), category = MAP_NPCMARK_FUNCTION}, 
{id = 42444, name = _t("[Tourney] Cross - Service competition"), category = MAP_NPCMARK_FUNCTION}, 
{id = 47528, name = _t("[Villa] Monthly Golden Week"), category = MAP_NPCMARK_FUNCTION}, 
{id = 30707, name = _t("[Villa] Holiday"), category = MAP_NPCMARK_FUNCTION}, 
{id = 29411, name = _t("[Villa] Goddess"), category = MAP_NPCMARK_FUNCTION}, 
{id = 50212, name = _t("[Villa] Anniversary Carnival"), category = MAP_NPCMARK_FUNCTION}, 
{id = 39769, name = _t("[Villa] Event"), category = MAP_NPCMARK_FUNCTION}, 
{id = 44451, name = _t("[Villa] Crisis! Saori Saints"), category = MAP_NPCMARK_FUNCTION}, 
{id = 44453, name = _t("[Villa] Critical! Goddess Saints"), category = MAP_NPCMARK_FUNCTION}, 
{id = 39671, name = _t("[Villa] Critical! Goddess of the mind"), category = MAP_NPCMARK_FUNCTION}, 
{id = 38428, name = _t("[Villa] Marriage - Divorce - Best friend"), category = MAP_NPCMARK_FUNCTION}, 
{id = 34575, name = _t("[Villa] Mentor"), category = MAP_NPCMARK_FUNCTION}}, 
[2005] = {
{id = 17439, name = _t("[Merchant] Bronze Crafter"), category = MAP_NPCMARK_FUNCTION}, 
{id = 17440, name = _t("[Merchant] White Silversmith"), category = MAP_NPCMARK_FUNCTION}, 
{id = 31003, name = _t("[Merchant] Dark crafter"), category = MAP_NPCMARK_FUNCTION}, 
{id = 28252, name = _t("[Merchant] Gold carpenter"), category = MAP_NPCMARK_FUNCTION}, 
{id = 34898, name = _t("[Merchant] Gold Messenger"), category = MAP_NPCMARK_FUNCTION}, 
{id = 39393, name = _t("[Merchant] Scale clothing"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14841, name = _t("[Merchant] Offerings clothing"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14686, name = _t("[Merchant] Silver guards"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14687, name = _t("[Merchant] Gold guards"), category = MAP_NPCMARK_FUNCTION}, 
{id = 37275, name = _t("[Merchant] Constellation"), category = MAP_NPCMARK_FUNCTION}, 
{id = 29190, name = _t("[Merchant] Star soul"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20313, name = _t("[Merchant] Light of Hope"), category = MAP_NPCMARK_FUNCTION}, 
{id = 11575, name = _t("[Merchant] Auctioneer"), category = MAP_NPCMARK_FUNCTION}, 
{id = 33262, name = _t("[Merchant] Ribbon"), category = MAP_NPCMARK_FUNCTION}, 
{id = 34694, name = _t("[Merchant] Belt"), category = MAP_NPCMARK_FUNCTION}, 
{id = 36329, name = _t("[Merchant] Artifact"), category = MAP_NPCMARK_FUNCTION}, 
{id = 43035, name = _t("[Merchant] Soul"), category = MAP_NPCMARK_FUNCTION}, 
{id = 18165, name = _t("[Merchant] Treasure"), category = MAP_NPCMARK_FUNCTION}, 
{id = 26471, name = _t("[Merchant] Title and Reputation"), category = MAP_NPCMARK_FUNCTION}, 
{id = 15578, name = _t("[Merchant] Oracle priest"), category = MAP_NPCMARK_FUNCTION}, 
{id = 31619, name = _t("[Merchant] Goddess of Mercy - Athenea"), category = MAP_NPCMARK_FUNCTION}, 
{id = 25893, name = _t("[Merchant] Heritage"), category = MAP_NPCMARK_FUNCTION}, 
{id = 16359, name = _t("[Merchant] Rider"), category = MAP_NPCMARK_FUNCTION}, 
{id = 17341, name = _t("[Merchant] Pet"), category = MAP_NPCMARK_FUNCTION}, 
{id = 32331, name = _t("[Merchant] Treasure Hunt"), category = MAP_NPCMARK_FUNCTION}, 
{id = 29306, name = _t("[Merchant] Security card"), category = MAP_NPCMARK_FUNCTION}, 
{id = 22955, name = _t("[Info] Ruler"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14799, name = _t("[Info] Guild"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14799, name = _t("[Info] Guild Alliance"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14799, name = _t("[Info] Banner guard"), category = MAP_NPCMARK_FUNCTION}, 
{id = 203238, name = _t("[Info] MAX! Unlimited Black Hole"), category = MAP_NPCMARK_FUNCTION}, 
{id = 13950, name = _t("[Info] Yihad Memories"), category = MAP_NPCMARK_FUNCTION}, 
{id = 13949, name = _t("[Info] Zodiac crisis - Sanctuary"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14420, name = _t("[Info] Atlantis - The Last Day of the Magic Star"), category = MAP_NPCMARK_FUNCTION}, 
{id = 50726, name = _t("[Info] Storm! Seal of the goddess"), category = MAP_NPCMARK_FUNCTION}, 
{id = 40463, name = _t("[Info] Resurrection! Myth battlefield "), category = MAP_NPCMARK_FUNCTION}, 
{id = 12839, name = _t("[Info] Gold trials - Counterattack - Lushan dream"), category = MAP_NPCMARK_FUNCTION}, 
{id = 211972, name = _t("[Info] Tried! Road of God"), category = MAP_NPCMARK_FUNCTION}, 
{id = 51273, name = _t("[Info] Crusade！World BOSS"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20220, name = _t("[Info] Kill Evil"), category = MAP_NPCMARK_FUNCTION}, 
{id = 41938, name = _t("[Info] Gold powder exchange"), category = MAP_NPCMARK_FUNCTION}, 
{id = 30079, name = _t("[Info] Mopping messengers"), category = MAP_NPCMARK_FUNCTION}, 
{id = 42851, name = _t("[Info] War God"), category = MAP_NPCMARK_FUNCTION}, 
{id = 9187, name = _t("[Info] Saint Goddess"), category = MAP_NPCMARK_FUNCTION}, 
{id = 201318, name = _t("[Info] Saint Seiya road"), category = MAP_NPCMARK_FUNCTION}, 
{id = 31592, name = _t("[Info] Sacred Commander"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8608, name = _t("[Core] Fate trials"), category = MAP_NPCMARK_FUNCTION}, 
{id = 30129, name = _t("[Core] Magic ring"), category = MAP_NPCMARK_FUNCTION}, 
{id = 41604, name = _t("[Core] Carnival"), category = MAP_NPCMARK_FUNCTION}, 
{id = 29138, name = _t("[Core] Welfare"), category = MAP_NPCMARK_FUNCTION}, 
{id = 35527, name = _t("[Core] Sanctuary Saints"), category = MAP_NPCMARK_FUNCTION}, 
{id = 32159, name = _t("[Core] Promotion - Fire"), category = MAP_NPCMARK_FUNCTION}, 
{id = 38489, name = _t("[Core] Event"), category = MAP_NPCMARK_FUNCTION}, 
{id = 18405, name = _t("[Tourney] Career change"), category = MAP_NPCMARK_FUNCTION}, 
{id = 16355, name = _t("[Tourney] Battlefield - Caitlinna"), category = MAP_NPCMARK_FUNCTION}, 
{id = 19317, name = _t("[Tourney] Battlefield rewards"), category = MAP_NPCMARK_FUNCTION}, 
{id = 34702, name = _t("[Tourney] Cloak Merchant"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14895, name = _t("[Tourney] Illusion"), category = MAP_NPCMARK_FUNCTION}, 
{id = 48412, name = _t("[Tourney] Galaxy Challenge - Cosmic Contest"), category = MAP_NPCMARK_FUNCTION}, 
{id = 42444, name = _t("[Tourney] Cross - Service competition"), category = MAP_NPCMARK_FUNCTION}, 
{id = 47528, name = _t("[Villa] Monthly Golden Week"), category = MAP_NPCMARK_FUNCTION}, 
{id = 30707, name = _t("[Villa] Holiday"), category = MAP_NPCMARK_FUNCTION}, 
{id = 29411, name = _t("[Villa] Goddess"), category = MAP_NPCMARK_FUNCTION}, 
{id = 50212, name = _t("[Villa] Anniversary Carnival"), category = MAP_NPCMARK_FUNCTION}, 
{id = 39769, name = _t("[Villa] Event"), category = MAP_NPCMARK_FUNCTION}, 
{id = 44451, name = _t("[Villa] Crisis! Saori Saints"), category = MAP_NPCMARK_FUNCTION}, 
{id = 44453, name = _t("[Villa] Critical! Goddess Saints"), category = MAP_NPCMARK_FUNCTION}, 
{id = 39671, name = _t("[Villa] Critical! Goddess of the mind"), category = MAP_NPCMARK_FUNCTION}, 
{id = 38428, name = _t("[Villa] Marriage - Divorce - Best friend"), category = MAP_NPCMARK_FUNCTION}, 
{id = 34575, name = _t("[Villa] Mentor"), category = MAP_NPCMARK_FUNCTION}}, 
[2006] = {
{id = 17439, name = _t("[Merchant] Bronze Crafter"), category = MAP_NPCMARK_FUNCTION}, 
{id = 17440, name = _t("[Merchant] White Silversmith"), category = MAP_NPCMARK_FUNCTION}, 
{id = 31003, name = _t("[Merchant] Dark crafter"), category = MAP_NPCMARK_FUNCTION}, 
{id = 28252, name = _t("[Merchant] Gold carpenter"), category = MAP_NPCMARK_FUNCTION}, 
{id = 34898, name = _t("[Merchant] Gold Messenger"), category = MAP_NPCMARK_FUNCTION}, 
{id = 39393, name = _t("[Merchant] Scale clothing"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14841, name = _t("[Merchant] Offerings clothing"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14686, name = _t("[Merchant] Silver guards"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14687, name = _t("[Merchant] Gold guards"), category = MAP_NPCMARK_FUNCTION}, 
{id = 37275, name = _t("[Merchant] Constellation"), category = MAP_NPCMARK_FUNCTION}, 
{id = 29190, name = _t("[Merchant] Star soul"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20313, name = _t("[Merchant] Light of Hope"), category = MAP_NPCMARK_FUNCTION}, 
{id = 11575, name = _t("[Merchant] Auctioneer"), category = MAP_NPCMARK_FUNCTION}, 
{id = 33262, name = _t("[Merchant] Ribbon"), category = MAP_NPCMARK_FUNCTION}, 
{id = 34694, name = _t("[Merchant] Belt"), category = MAP_NPCMARK_FUNCTION}, 
{id = 36329, name = _t("[Merchant] Artifact"), category = MAP_NPCMARK_FUNCTION}, 
{id = 43035, name = _t("[Merchant] Soul"), category = MAP_NPCMARK_FUNCTION}, 
{id = 18165, name = _t("[Merchant] Treasure"), category = MAP_NPCMARK_FUNCTION}, 
{id = 26471, name = _t("[Merchant] Title and Reputation"), category = MAP_NPCMARK_FUNCTION}, 
{id = 15578, name = _t("[Merchant] Oracle priest"), category = MAP_NPCMARK_FUNCTION}, 
{id = 31619, name = _t("[Merchant] Goddess of Mercy - Athenea"), category = MAP_NPCMARK_FUNCTION}, 
{id = 25893, name = _t("[Merchant] Heritage"), category = MAP_NPCMARK_FUNCTION}, 
{id = 16359, name = _t("[Merchant] Rider"), category = MAP_NPCMARK_FUNCTION}, 
{id = 17341, name = _t("[Merchant] Pet"), category = MAP_NPCMARK_FUNCTION}, 
{id = 32331, name = _t("[Merchant] Treasure Hunt"), category = MAP_NPCMARK_FUNCTION}, 
{id = 29306, name = _t("[Merchant] Security card"), category = MAP_NPCMARK_FUNCTION}, 
{id = 22955, name = _t("[Info] Ruler"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14799, name = _t("[Info] Guild"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14799, name = _t("[Info] Guild Alliance"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14799, name = _t("[Info] Banner guard"), category = MAP_NPCMARK_FUNCTION}, 
{id = 203238, name = _t("[Info] MAX! Unlimited Black Hole"), category = MAP_NPCMARK_FUNCTION}, 
{id = 13950, name = _t("[Info] Yihad Memories"), category = MAP_NPCMARK_FUNCTION}, 
{id = 13949, name = _t("[Info] Zodiac crisis - Sanctuary"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14420, name = _t("[Info] Atlantis - The Last Day of the Magic Star"), category = MAP_NPCMARK_FUNCTION}, 
{id = 50726, name = _t("[Info] Storm! Seal of the goddess"), category = MAP_NPCMARK_FUNCTION}, 
{id = 40463, name = _t("[Info] Resurrection! Myth battlefield "), category = MAP_NPCMARK_FUNCTION}, 
{id = 12839, name = _t("[Info] Gold trials - Counterattack - Lushan dream"), category = MAP_NPCMARK_FUNCTION}, 
{id = 211972, name = _t("[Info] Tried! Road of God"), category = MAP_NPCMARK_FUNCTION}, 
{id = 51273, name = _t("[Info] Crusade！World BOSS"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20220, name = _t("[Info] Kill Evil"), category = MAP_NPCMARK_FUNCTION}, 
{id = 41938, name = _t("[Info] Gold powder exchange"), category = MAP_NPCMARK_FUNCTION}, 
{id = 30079, name = _t("[Info] Mopping messengers"), category = MAP_NPCMARK_FUNCTION}, 
{id = 42851, name = _t("[Info] War God"), category = MAP_NPCMARK_FUNCTION}, 
{id = 9187, name = _t("[Info] Saint Goddess"), category = MAP_NPCMARK_FUNCTION}, 
{id = 201318, name = _t("[Info] Saint Seiya road"), category = MAP_NPCMARK_FUNCTION}, 
{id = 31592, name = _t("[Info] Sacred Commander"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8608, name = _t("[Core] Fate trials"), category = MAP_NPCMARK_FUNCTION}, 
{id = 30129, name = _t("[Core] Magic ring"), category = MAP_NPCMARK_FUNCTION}, 
{id = 41604, name = _t("[Core] Carnival"), category = MAP_NPCMARK_FUNCTION}, 
{id = 29138, name = _t("[Core] Welfare"), category = MAP_NPCMARK_FUNCTION}, 
{id = 35527, name = _t("[Core] Sanctuary Saints"), category = MAP_NPCMARK_FUNCTION}, 
{id = 32159, name = _t("[Core] Promotion - Fire"), category = MAP_NPCMARK_FUNCTION}, 
{id = 38489, name = _t("[Core] Event"), category = MAP_NPCMARK_FUNCTION}, 
{id = 18405, name = _t("[Tourney] Career change"), category = MAP_NPCMARK_FUNCTION}, 
{id = 16355, name = _t("[Tourney] Battlefield - Caitlinna"), category = MAP_NPCMARK_FUNCTION}, 
{id = 19317, name = _t("[Tourney] Battlefield rewards"), category = MAP_NPCMARK_FUNCTION}, 
{id = 34702, name = _t("[Tourney] Cloak Merchant"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14895, name = _t("[Tourney] Illusion"), category = MAP_NPCMARK_FUNCTION}, 
{id = 48412, name = _t("[Tourney] Galaxy Challenge - Cosmic Contest"), category = MAP_NPCMARK_FUNCTION}, 
{id = 42444, name = _t("[Tourney] Cross - Service competition"), category = MAP_NPCMARK_FUNCTION}, 
{id = 47528, name = _t("[Villa] Monthly Golden Week"), category = MAP_NPCMARK_FUNCTION}, 
{id = 30707, name = _t("[Villa] Holiday"), category = MAP_NPCMARK_FUNCTION}, 
{id = 29411, name = _t("[Villa] Goddess"), category = MAP_NPCMARK_FUNCTION}, 
{id = 50212, name = _t("[Villa] Anniversary Carnival"), category = MAP_NPCMARK_FUNCTION}, 
{id = 39769, name = _t("[Villa] Event"), category = MAP_NPCMARK_FUNCTION}, 
{id = 44451, name = _t("[Villa] Crisis! Saori Saints"), category = MAP_NPCMARK_FUNCTION}, 
{id = 44453, name = _t("[Villa] Critical! Goddess Saints"), category = MAP_NPCMARK_FUNCTION}, 
{id = 39671, name = _t("[Villa] Critical! Goddess of the mind"), category = MAP_NPCMARK_FUNCTION}, 
{id = 38428, name = _t("[Villa] Marriage - Divorce - Best friend"), category = MAP_NPCMARK_FUNCTION}, 
{id = 34575, name = _t("[Villa] Mentor"), category = MAP_NPCMARK_FUNCTION}}, 
[2007] = {
{id = 17439, name = _t("[Merchant] Bronze Crafter"), category = MAP_NPCMARK_FUNCTION}, 
{id = 17440, name = _t("[Merchant] White Silversmith"), category = MAP_NPCMARK_FUNCTION}, 
{id = 31003, name = _t("[Merchant] Dark crafter"), category = MAP_NPCMARK_FUNCTION}, 
{id = 28252, name = _t("[Merchant] Gold carpenter"), category = MAP_NPCMARK_FUNCTION}, 
{id = 34898, name = _t("[Merchant] Gold Messenger"), category = MAP_NPCMARK_FUNCTION}, 
{id = 39393, name = _t("[Merchant] Scale clothing"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14841, name = _t("[Merchant] Offerings clothing"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14686, name = _t("[Merchant] Silver guards"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14687, name = _t("[Merchant] Gold guards"), category = MAP_NPCMARK_FUNCTION}, 
{id = 37275, name = _t("[Merchant] Constellation"), category = MAP_NPCMARK_FUNCTION}, 
{id = 29190, name = _t("[Merchant] Star soul"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20313, name = _t("[Merchant] Light of Hope"), category = MAP_NPCMARK_FUNCTION}, 
{id = 11575, name = _t("[Merchant] Auctioneer"), category = MAP_NPCMARK_FUNCTION}, 
{id = 33262, name = _t("[Merchant] Ribbon"), category = MAP_NPCMARK_FUNCTION}, 
{id = 34694, name = _t("[Merchant] Belt"), category = MAP_NPCMARK_FUNCTION}, 
{id = 36329, name = _t("[Merchant] Artifact"), category = MAP_NPCMARK_FUNCTION}, 
{id = 43035, name = _t("[Merchant] Soul"), category = MAP_NPCMARK_FUNCTION}, 
{id = 18165, name = _t("[Merchant] Treasure"), category = MAP_NPCMARK_FUNCTION}, 
{id = 26471, name = _t("[Merchant] Title and Reputation"), category = MAP_NPCMARK_FUNCTION}, 
{id = 15578, name = _t("[Merchant] Oracle priest"), category = MAP_NPCMARK_FUNCTION}, 
{id = 31619, name = _t("[Merchant] Goddess of Mercy - Athenea"), category = MAP_NPCMARK_FUNCTION}, 
{id = 25893, name = _t("[Merchant] Heritage"), category = MAP_NPCMARK_FUNCTION}, 
{id = 16359, name = _t("[Merchant] Rider"), category = MAP_NPCMARK_FUNCTION}, 
{id = 17341, name = _t("[Merchant] Pet"), category = MAP_NPCMARK_FUNCTION}, 
{id = 32331, name = _t("[Merchant] Treasure Hunt"), category = MAP_NPCMARK_FUNCTION}, 
{id = 29306, name = _t("[Merchant] Security card"), category = MAP_NPCMARK_FUNCTION}, 
{id = 22955, name = _t("[Info] Ruler"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14799, name = _t("[Info] Guild"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14799, name = _t("[Info] Guild Alliance"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14799, name = _t("[Info] Banner guard"), category = MAP_NPCMARK_FUNCTION}, 
{id = 203238, name = _t("[Info] MAX! Unlimited Black Hole"), category = MAP_NPCMARK_FUNCTION}, 
{id = 13950, name = _t("[Info] Yihad Memories"), category = MAP_NPCMARK_FUNCTION}, 
{id = 13949, name = _t("[Info] Zodiac crisis - Sanctuary"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14420, name = _t("[Info] Atlantis - The Last Day of the Magic Star"), category = MAP_NPCMARK_FUNCTION}, 
{id = 50726, name = _t("[Info] Storm! Seal of the goddess"), category = MAP_NPCMARK_FUNCTION}, 
{id = 40463, name = _t("[Info] Resurrection! Myth battlefield "), category = MAP_NPCMARK_FUNCTION}, 
{id = 12839, name = _t("[Info] Gold trials - Counterattack - Lushan dream"), category = MAP_NPCMARK_FUNCTION}, 
{id = 211972, name = _t("[Info] Tried! Road of God"), category = MAP_NPCMARK_FUNCTION}, 
{id = 51273, name = _t("[Info] Crusade！World BOSS"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20220, name = _t("[Info] Kill Evil"), category = MAP_NPCMARK_FUNCTION}, 
{id = 41938, name = _t("[Info] Gold powder exchange"), category = MAP_NPCMARK_FUNCTION}, 
{id = 30079, name = _t("[Info] Mopping messengers"), category = MAP_NPCMARK_FUNCTION}, 
{id = 42851, name = _t("[Info] War God"), category = MAP_NPCMARK_FUNCTION}, 
{id = 9187, name = _t("[Info] Saint Goddess"), category = MAP_NPCMARK_FUNCTION}, 
{id = 201318, name = _t("[Info] Saint Seiya road"), category = MAP_NPCMARK_FUNCTION}, 
{id = 31592, name = _t("[Info] Sacred Commander"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8608, name = _t("[Core] Fate trials"), category = MAP_NPCMARK_FUNCTION}, 
{id = 30129, name = _t("[Core] Magic ring"), category = MAP_NPCMARK_FUNCTION}, 
{id = 41604, name = _t("[Core] Carnival"), category = MAP_NPCMARK_FUNCTION}, 
{id = 29138, name = _t("[Core] Welfare"), category = MAP_NPCMARK_FUNCTION}, 
{id = 35527, name = _t("[Core] Sanctuary Saints"), category = MAP_NPCMARK_FUNCTION}, 
{id = 32159, name = _t("[Core] Promotion - Fire"), category = MAP_NPCMARK_FUNCTION}, 
{id = 38489, name = _t("[Core] Event"), category = MAP_NPCMARK_FUNCTION}, 
{id = 18405, name = _t("[Tourney] Career change"), category = MAP_NPCMARK_FUNCTION}, 
{id = 16355, name = _t("[Tourney] Battlefield - Caitlinna"), category = MAP_NPCMARK_FUNCTION}, 
{id = 19317, name = _t("[Tourney] Battlefield rewards"), category = MAP_NPCMARK_FUNCTION}, 
{id = 34702, name = _t("[Tourney] Cloak Merchant"), category = MAP_NPCMARK_FUNCTION}, 
{id = 14895, name = _t("[Tourney] Illusion"), category = MAP_NPCMARK_FUNCTION}, 
{id = 48412, name = _t("[Tourney] Galaxy Challenge - Cosmic Contest"), category = MAP_NPCMARK_FUNCTION}, 
{id = 42444, name = _t("[Tourney] Cross - Service competition"), category = MAP_NPCMARK_FUNCTION}, 
{id = 47528, name = _t("[Villa] Monthly Golden Week"), category = MAP_NPCMARK_FUNCTION}, 
{id = 30707, name = _t("[Villa] Holiday"), category = MAP_NPCMARK_FUNCTION}, 
{id = 29411, name = _t("[Villa] Goddess"), category = MAP_NPCMARK_FUNCTION}, 
{id = 50212, name = _t("[Villa] Anniversary Carnival"), category = MAP_NPCMARK_FUNCTION}, 
{id = 39769, name = _t("[Villa] Event"), category = MAP_NPCMARK_FUNCTION}, 
{id = 44451, name = _t("[Villa] Crisis! Saori Saints"), category = MAP_NPCMARK_FUNCTION}, 
{id = 44453, name = _t("[Villa] Critical! Goddess Saints"), category = MAP_NPCMARK_FUNCTION}, 
{id = 39671, name = _t("[Villa] Critical! Goddess of the mind"), category = MAP_NPCMARK_FUNCTION}, 
{id = 38428, name = _t("[Villa] Marriage - Divorce - Best friend"), category = MAP_NPCMARK_FUNCTION}, 
{id = 34575, name = _t("[Villa] Mentor"), category = MAP_NPCMARK_FUNCTION}}, 
[2009] = {
{id = 13599, name = _t("Artisan"), category = MAP_NPCMARK_FUNCTION}}}
NpcList[25] = {instance = 103, 
list = {
{id = 8522, name = _t("Base Architect"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8541, name = _t("Base Store"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8530, name = _t("Base Warehouse"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8550, name = _t("Base Training Ground"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8566, name = _t("Base altar"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8556, name = _t("Base Shop Manager"), category = MAP_NPCMARK_FUNCTION}, 
{id = 17857, name = _t("Legionary cultivation"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20614, name = _t("Hermes"), category = MAP_NPCMARK_IMPORT_TASK}, 
{id = 213142, name = _t("Legion Goddess"), category = MAP_NPCMARK_IMPORT_TASK}}}
NpcList[26] = {instance = 104, 
list = {
{id = 8523, name = _t("Base Architect"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8540, name = _t("Base Store"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8531, name = _t("Base Warehouse"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8549, name = _t("Base Training Ground"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8567, name = _t("Base altar"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8557, name = _t("Base Shop Manager"), category = MAP_NPCMARK_FUNCTION}, 
{id = 17857, name = _t("Legionary cultivation"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20614, name = _t("Hermes"), category = MAP_NPCMARK_IMPORT_TASK}, 
{id = 213143, name = _t("Legion Goddess"), category = MAP_NPCMARK_IMPORT_TASK}}}
NpcList[27] = {instance = 105, 
list = {
{id = 8524, name = _t("Base Architect"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8539, name = _t("Base Store"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8532, name = _t("Base Warehouse"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8548, name = _t("Base Training Ground"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8569, name = _t("Base altar"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8558, name = _t("Base Shop Manager"), category = MAP_NPCMARK_FUNCTION}, 
{id = 17857, name = _t("Legionary cultivation"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20614, name = _t("Hermes"), category = MAP_NPCMARK_IMPORT_TASK}, 
{id = 213144, name = _t("Legion Goddess"), category = MAP_NPCMARK_IMPORT_TASK}}}
NpcList[28] = {instance = 106, 
list = {
{id = 8521, name = _t("Base Architect"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8538, name = _t("Base Store"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8529, name = _t("Base Warehouse"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8547, name = _t("Base Training Ground"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8565, name = _t("Base altar"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8559, name = _t("Base Shop Manager"), category = MAP_NPCMARK_FUNCTION}, 
{id = 17857, name = _t("Legionary cultivation"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20614, name = _t("Hermes"), category = MAP_NPCMARK_IMPORT_TASK}, 
{id = 213169, name = _t("Legion Goddess"), category = MAP_NPCMARK_IMPORT_TASK}}}
NpcList[29] = {instance = 107, 
list = {
{id = 8520, name = _t("Base Architect"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8537, name = _t("Base Store"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8528, name = _t("Base Warehouse"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8546, name = _t("Base Training Ground"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8564, name = _t("Base altar"), category = MAP_NPCMARK_FUNCTION}, 
{id = 8555, name = _t("Base Shop Manager"), category = MAP_NPCMARK_FUNCTION}, 
{id = 17857, name = _t("Legionary cultivation"), category = MAP_NPCMARK_FUNCTION}, 
{id = 20614, name = _t("Hermes"), category = MAP_NPCMARK_IMPORT_TASK}, 
{id = 213170, name = _t("Legion Goddess"), category = MAP_NPCMARK_IMPORT_TASK}}}

