--[[ @i18n achievement ]]
local _t = require("i18n").context("achievement")
achievement_league = {
    [1001]=
        {
        name = _t"lvl 1", 
        type_level3 = 1, 
        points = 10, 
        award = 0, 
        pre_achiev = 0, 
        cover_achiev = 0, 
        broadcast = 0, 
        hiden = 0, 
        icon = "圣衣箱子5.dds", 
        desc = _t"lvl up lvl 1", 
        informal = 0, 
},
    [1002]=
        {
        name = _t"lvl 2", 
        type_level3 = 1, 
        points = 10, 
        award = 0, 
        pre_achiev = 0, 
        cover_achiev = 0, 
        broadcast = 0, 
        hiden = 0, 
        icon = "圣衣箱子5.dds", 
        desc = _t"lvl up lvl 2", 
        informal = 0, 
},
    [1003]=
        {
        name = _t"lvl 3", 
        type_level3 = 1, 
        points = 10, 
        award = 0, 
        pre_achiev = 0, 
        cover_achiev = 0, 
        broadcast = 0, 
        hiden = 0, 
        icon = "圣衣箱子5.dds", 
        desc = _t"lvl up lvl 3", 
        informal = 0, 
},
    [1011]=
        {
        name = _t"10 people", 
        type_level3 = 1, 
        points = 10, 
        award = 0, 
        pre_achiev = 0, 
        cover_achiev = 0, 
        broadcast = 0, 
        hiden = 0, 
        icon = "圣衣箱子5.dds", 
        desc = _t"reached 10 people,",
        informal = 0, 
},
    [1012]=
        {
        name = _t"50 people", 
        type_level3 = 1, 
        points = 10, 
        award = 0, 
        pre_achiev = 0, 
        cover_achiev = 0, 
        broadcast = 0, 
        hiden = 0, 
        icon = "圣衣箱子5.dds", 
        desc = _t"reached 50 people,",
        informal = 0, 
},
    [1013]=
        {
        name = _t"100 people",
        type_level3 = 1, 
        points = 10, 
        award = 0, 
        pre_achiev = 0, 
        cover_achiev = 0, 
        broadcast = 0, 
        hiden = 0, 
        icon = "圣衣箱子5.dds", 
        desc = _t"reached 100 people,",
        informal = 0, 
},
    [2001]=
        {
        name = _t"daily: 5 times",
        type_level3 = 1, 
        points = 10, 
        award = 0, 
        pre_achiev = 0, 
        cover_achiev = 0, 
        broadcast = 0, 
        hiden = 0, 
        icon = "圣衣箱子5.dds", 
        desc = _t"complete daily 5 times",
        informal = 0, 
},
    [2002]=
        {
        name = _t"daily: 10 times",
        type_level3 = 1, 
        points = 10, 
        award = 0, 
        pre_achiev = 0, 
        cover_achiev = 0, 
        broadcast = 0, 
        hiden = 0, 
        icon = "圣衣箱子5.dds", 
        desc = _t"complete daily 10 times",
        informal = 0, 
},
    [2003]=
        {
        name = _t"Zhou Chang: 5 times",
        type_level3 = 1, 
        points = 10, 
        award = 0, 
        pre_achiev = 0, 
        cover_achiev = 0, 
        broadcast = 0, 
        hiden = 0, 
        icon = "圣衣箱子5.dds", 
        desc = _t"complete week 5 times",
        informal = 0, 
},
    [2004]=
        {
        name = _t"Zhou Chang: 10",
        type_level3 = 1, 
        points = 10, 
        award = 0, 
        pre_achiev = 0, 
        cover_achiev = 0, 
        broadcast = 0, 
        hiden = 0, 
        icon = "圣衣箱子5.dds", 
        desc = _t"complete week 10 times",
        informal = 0, 
},
    [2011]=
        {
        name = _t"main build: lvl 1", 
        type_level3 = 1, 
        points = 10, 
        award = 0, 
        pre_achiev = 0, 
        cover_achiev = 0, 
        broadcast = 0, 
        hiden = 0, 
        icon = "圣衣箱子5.dds", 
        desc = _t"main build reach lvl 1", 
        informal = 0, 
},
    [2012]=
        {
        name = _t"main build: lvl 2", 
        type_level3 = 1, 
        points = 10, 
        award = 0, 
        pre_achiev = 0, 
        cover_achiev = 0, 
        broadcast = 0, 
        hiden = 0, 
        icon = "圣衣箱子5.dds", 
        desc = _t"main build reach lvl 2", 
        informal = 0, 
},
    [2013]=
        {
        name = _t"main build: lvl 3", 
        type_level3 = 1, 
        points = 10, 
        award = 0, 
        pre_achiev = 0, 
        cover_achiev = 0, 
        broadcast = 0, 
        hiden = 0, 
        icon = "圣衣箱子5.dds", 
        desc = _t"main build reach lvl 3", 
        informal = 0, 
},
    [3001]=
        {
        name = _t"Legion:Atlantis",
        type_level3 = 1, 
        points = 10, 
        award = 0, 
        pre_achiev = 0, 
        cover_achiev = 0, 
        broadcast = 0, 
        hiden = 0, 
        icon = "圣衣箱子5.dds", 
        desc = _t"4+ team members complete Atlantis",
        informal = 0, 
},
    [3002]=
        {
        name = _t"Legion:Gold trials",
        type_level3 = 1, 
        points = 10, 
        award = 0, 
        pre_achiev = 0, 
        cover_achiev = 0, 
        broadcast = 0, 
        hiden = 0, 
        icon = "圣衣箱子5.dds", 
        desc = _t"4+ team members complete Gold trials",
        informal = 0, 
},
    [3003]=
        {
        name = _t"Legion:Defend yarns", 
        type_level3 = 1, 
        points = 10, 
        award = 0, 
        pre_achiev = 0, 
        cover_achiev = 0, 
        broadcast = 0, 
        hiden = 0, 
        icon = "圣衣箱子5.dds", 
        desc = _t"4+ team members complete Defend yarns", 
        informal = 0, 
},
    [3004]=
        {
        name = _t"Legion:Jihad Memories",
        type_level3 = 1, 
        points = 10, 
        award = 0, 
        pre_achiev = 0, 
        cover_achiev = 0, 
        broadcast = 0, 
        hiden = 0, 
        icon = "圣衣箱子5.dds", 
        desc = _t"4+ team members complete Jihad Memories",
        informal = 0, 
},
}